# -*- coding: utf-8 -*-
"""Music_generation_AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4r5tJ1C_vpm-AgrcsGSz77Rif91Q_9b
"""

!pip install music21 tensorflow

from music21 import converter, instrument, note, chord, stream
import glob
import numpy as np
import random

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM
from tensorflow.keras.utils import to_categorical

notes = []

# Read all MIDI files
for file in glob.glob("/content/*.mid*"):

    print("Loading:", file)

    midi = converter.parse(file)

    notes_to_parse = midi.flatten().notes

    for element in notes_to_parse:

        # Single notes
        if isinstance(element, note.Note):
            notes.append(str(element.pitch))

        # Chords
        elif isinstance(element, chord.Chord):
            notes.append('.'.join(str(n) for n in element.normalOrder))

print("\nTotal Notes Extracted:", len(notes))
print(notes[:20])

# Unique notes
pitchnames = sorted(set(notes))

# Convert notes to integers
note_to_int = dict((note, number) for number, note in enumerate(pitchnames))

sequence_length = 50

network_input = []
network_output = []

for i in range(len(notes) - sequence_length):

    sequence_in = notes[i:i + sequence_length]
    sequence_out = notes[i + sequence_length]

    network_input.append([note_to_int[char] for char in sequence_in])
    network_output.append(note_to_int[sequence_out])

n_patterns = len(network_input)

# Reshape input
network_input = np.reshape(
    network_input,
    (n_patterns, sequence_length, 1)
)

# Normalize
network_input = network_input / float(len(pitchnames))

# One-hot encode output
network_output = to_categorical(network_output)

print("Total Patterns:", n_patterns)
print("Unique Notes:", len(pitchnames))

model = Sequential()

model.add(LSTM(
    256,
    input_shape=(network_input.shape[1], network_input.shape[2]),
    return_sequences=True
))

model.add(Dropout(0.3))

model.add(LSTM(256))

model.add(Dense(256))

model.add(Dropout(0.3))

model.add(Dense(len(pitchnames), activation='softmax'))

model.compile(
    loss='categorical_crossentropy',
    optimizer='adam'
)

model.summary()

model.fit(
    network_input,
    network_output,
    epochs=50,
    batch_size=64
)

start = random.randint(0, len(network_input)-1)

pattern = network_input[start]

prediction_output = []

int_to_note = dict(
    (number, note) for number, note in enumerate(pitchnames)
)

# Generate 200 notes
for note_index in range(200):

    prediction_input = np.reshape(pattern, (1, len(pattern), 1))
    prediction_input = prediction_input / float(len(pitchnames))

    prediction = model.predict(prediction_input, verbose=0)

    index = np.argmax(prediction)

    result = int_to_note[index]

    prediction_output.append(result)

    pattern = np.append(pattern, index)
    pattern = pattern[1:]

print(prediction_output[:20])

offset = 0
output_notes = []

for pattern in prediction_output:

    # Chord
    if ('.' in pattern) or pattern.isdigit():

        notes_in_chord = pattern.split('.')
        notes = []

        for current_note in notes_in_chord:

            new_note = note.Note(int(current_note))
            new_note.storedInstrument = instrument.Piano()
            notes.append(new_note)

        new_chord = chord.Chord(notes)
        new_chord.offset = offset
        output_notes.append(new_chord)

    # Single Note
    else:

        new_note = note.Note(pattern)
        new_note.offset = offset
        new_note.storedInstrument = instrument.Piano()
        output_notes.append(new_note)

    offset += 0.5

midi_stream = stream.Stream(output_notes)

midi_stream.write('midi', fp='generated_music.mid')

print("Music Generated Successfully!")

from google.colab import files

files.download('generated_music.mid')

model.save("music_model.h5")

from google.colab import files
files.download("music_model.h5")

readme_content = """
# 🎵 AI Music Generation using LSTM

## Project Overview
This project generates musical note sequences using a Long Short-Term Memory (LSTM) neural network trained on MIDI music data. The model learns patterns from existing music and creates new melodies automatically.

## Features
- MIDI file preprocessing using Music21
- Note sequence extraction
- LSTM-based deep learning model
- Automatic music generation
- Export generated music as MIDI files

## Technologies Used
- Python
- TensorFlow / Keras
- Music21
- NumPy
- Google Colab

## Project Workflow
1. Collect MIDI music files.
2. Extract notes and chords using Music21.
3. Convert notes into numerical sequences.
4. Train an LSTM neural network.
5. Generate new note sequences.
6. Convert generated notes back into MIDI format.

## Model Architecture
- LSTM Layers
- Dropout Layers
- Dense Output Layer
- Softmax Activation

## Results
The trained model successfully generates new musical compositions based on learned musical patterns from the training dataset.

## How to Run
1. Install required libraries:
   pip install -r requirements.txt

2. Open the notebook in Google Colab.

3. Run all cells sequentially.

4. Generate new music and download the output MIDI file.

## Future Improvements
- Train on larger datasets
- Support multiple music genres
- Deploy as a web application
- Add real-time music generation

## Author
Developed as part of an AI Music Generation Internship Project.
"""

with open("README.md", "w") as f:
    f.write(readme_content)

print("README.md created successfully!")

from google.colab import files
files.download("README.md")

requirements = """
tensorflow
numpy
music21
matplotlib
keras
"""

with open("requirements.txt", "w") as f:
    f.write(requirements)

print("requirements.txt created successfully!")

files.download("requirements.txt")

from google.colab import files
files.download("generated_music.mid")

